// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Boot address specified in decimal to avoid single quote in number, which
// causes parsing errors of this file in Riviera.
+define+BOOT_ADDR=2147483648 // 32'h8000_0000
+define+TRACE_EXECUTION
+define+RVFI
+define+SIM

#${DV_AZADI_TSMC}/random_tests/depencs/

// Shared lowRISC code
+incdir+${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/prim/rtl
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/prim/rtl/prim_assert.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/prim/rtl/prim_lfsr.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/prim/rtl/prim_secded_28_22_enc.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/prim/rtl/prim_secded_28_22_dec.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/prim/rtl/prim_secded_39_32_enc.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/prim/rtl/prim_secded_39_32_dec.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/prim/rtl/prim_secded_72_64_enc.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/prim/rtl/prim_secded_72_64_dec.sv

// Until this list is generated by FuseSoC, we have to use manually generated
// wrappers around the prim_* modules to instantiate the prim_generic_* ones,
// see https://github.com/lowRISC/ibex/issues/893.
${DV_DIR}/common/prim/prim_pkg.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/prim_generic/rtl/prim_generic_ram_1p.sv
${DV_DIR}/common/prim/prim_ram_1p.sv
//${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/prim_generic/rtl/prim_generic_clock_gating.sv
${DV_DIR}/common/prim/prim_clock_gating.sv

// ibex CORE RTL files
+incdir+${DV_AZADI_TSMC}/random_tests/depencs
+incdir+${PRJ_DIR}


// OLD FILES
//+incdir+${FPU_DIR}/src
//+incdir+${FPU_DIR}/src/common_cells/src
//+incdir+${FPU_DIR}/src/common_cells/include
//+incdir+${FPU_DIR}/src/fpu_div_sqrt_mvp/hdl
//${FPU_DIR}/src/fpnew_pkg.sv
//${FPU_DIR}/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
//${FPU_DIR}/src/common_cells/src/cf_math_pkg.sv
//${PRJ_DIR}/rtl/ibex_pkg.sv
//${PRJ_DIR}/rtl/ibex_tracer_pkg.sv
//${PRJ_DIR}/rtl/ibex_tracer.sv
//${PRJ_DIR}/rtl/ibex_alu.sv
//${PRJ_DIR}/rtl/ibex_branch_predict.sv
//${PRJ_DIR}/rtl/ibex_compressed_decoder.sv
//${PRJ_DIR}/rtl/ibex_controller.sv
//${PRJ_DIR}/rtl/ibex_csr.sv
//${PRJ_DIR}/rtl/ibex_cs_registers.sv
//${PRJ_DIR}/rtl/ibex_counter.sv
//${PRJ_DIR}/rtl/ibex_decoder.sv
//${PRJ_DIR}/rtl/ibex_dummy_instr.sv
//${PRJ_DIR}/rtl/ibex_ex_block.sv
//${PRJ_DIR}/rtl/ibex_wb_stage.sv
//${PRJ_DIR}/rtl/ibex_id_stage.sv
//${PRJ_DIR}/rtl/ibex_icache.sv
//${PRJ_DIR}/rtl/ibex_if_stage.sv
//${PRJ_DIR}/rtl/ibex_load_store_unit.sv
//${PRJ_DIR}/rtl/ibex_multdiv_slow.sv
//${PRJ_DIR}/rtl/ibex_multdiv_fast.sv
//${PRJ_DIR}/rtl/ibex_prefetch_buffer.sv
//${PRJ_DIR}/rtl/ibex_fetch_fifo.sv
//${PRJ_DIR}/rtl/ibex_register_file_ff.sv
//${PRJ_DIR}/rtl/ibex_register_file_fpga.sv
//${PRJ_DIR}/rtl/ibex_register_file_latch.sv
//${PRJ_DIR}/rtl/ibex_pmp.sv
//${PRJ_DIR}/rtl/ibex_core.sv
//${PRJ_DIR}/rtl/ibex_core_tracing.sv
//${PRJ_DIR}/rtl/ibex_fp_register_file_ff.sv

// LATEST FILES
${PRJ_DIR}/brq_pkg.sv
${PRJ_DIR}/ibex_tracer_pkg.sv
${PRJ_DIR}/ibex_tracer.sv
${PRJ_DIR}/cf_math_pkg.sv
${PRJ_DIR}/gpio_reg_pkg.sv
${PRJ_DIR}/fpnew_pkg.sv
${PRJ_DIR}/prim_pkg.sv
${PRJ_DIR}/prim_util_pkg.sv
${PRJ_DIR}/rv_plic_reg_pkg.sv
${PRJ_DIR}/rv_timer_reg_pkg.sv
${PRJ_DIR}/tlul_pkg.sv
${PRJ_DIR}/tlul_xbar_main_pkg.sv
${PRJ_DIR}/tlul_xbar_periph_pkg.sv
${PRJ_DIR}/defs_div_sqrt_mvp.sv
${PRJ_DIR}/spi_defines.sv
${PRJ_DIR}/brq_core.sv
${PRJ_DIR}/ibex_core_tracing.sv
${PRJ_DIR}/brq_counter.sv
${PRJ_DIR}/brq_cs_registers.sv
${PRJ_DIR}/brq_csr.sv
${PRJ_DIR}/brq_exu_alu.sv
${PRJ_DIR}/brq_exu_multdiv_fast.sv
${PRJ_DIR}/brq_exu_multdiv_slow.sv
${PRJ_DIR}/brq_exu.sv
${PRJ_DIR}/brq_fp_register_file_ff.sv
${PRJ_DIR}/brq_idu_controller.sv
${PRJ_DIR}/brq_idu_decoder.sv
${PRJ_DIR}/brq_idu.sv
${PRJ_DIR}/brq_ifu_compressed_decoder.sv
${PRJ_DIR}/brq_ifu_fifo.sv
${PRJ_DIR}/brq_ifu_prefetch_buffer.sv
${PRJ_DIR}/brq_ifu.sv
${PRJ_DIR}/brq_lsu.sv
${PRJ_DIR}/brq_register_file_ff.sv
${PRJ_DIR}/brq_wbu.sv
${PRJ_DIR}/buffer_array.sv
${PRJ_DIR}/buffer_control.sv
${PRJ_DIR}/clk_counter.sv
${PRJ_DIR}/control_mvp.sv
${PRJ_DIR}/data_mem_top.sv
${PRJ_DIR}/div_sqrt_top_mvp.sv
${PRJ_DIR}/fifo_async.sv
${PRJ_DIR}/fifo_sync.sv
${PRJ_DIR}/fpnew_cast_multi.sv
${PRJ_DIR}/fpnew_classifier.sv
${PRJ_DIR}/fpnew_divsqrt_multi.sv
${PRJ_DIR}/fpnew_fma_multi.sv
${PRJ_DIR}/fpnew_fma.sv
${PRJ_DIR}/fpnew_noncomp.sv
${PRJ_DIR}/fpnew_opgroup_block.sv
${PRJ_DIR}/fpnew_opgroup_fmt_slice.sv
${PRJ_DIR}/fpnew_opgroup_multifmt_slice.sv
${PRJ_DIR}/fpnew_rounding.sv
${PRJ_DIR}/fpnew_top.sv
${PRJ_DIR}/gpio_reg_top.sv
${PRJ_DIR}/gpio.sv
//${PRJ_DIR}/ibex_configs.yaml
${PRJ_DIR}/iccm_controller.sv
${PRJ_DIR}/instr_mem_top.sv
${PRJ_DIR}/iteration_div_sqrt_mvp.sv
${PRJ_DIR}/lzc.sv
${PRJ_DIR}/norm_div_sqrt_mvp.sv
${PRJ_DIR}/nrbd_nrsc_mvp.sv
${PRJ_DIR}/PAD100MTB.v
${PRJ_DIR}/preprocess_mvp.sv
${PRJ_DIR}/prim_filter_ctr.sv
${PRJ_DIR}/prim_generic_clock_gating.sv
${PRJ_DIR}/prim_generic_flop_2sync.sv
${PRJ_DIR}/prim_generic_flop.sv
${PRJ_DIR}/prim_intr_hw.sv
${PRJ_DIR}/prim_subreg_arb.sv
${PRJ_DIR}/prim_subreg_ext.sv
${PRJ_DIR}/prim_subreg.sv
${PRJ_DIR}/pwm_channel.sv
${PRJ_DIR}/pwm.sv
${PRJ_DIR}/pwm_top.sv
${PRJ_DIR}/qspi_receiver.sv
${PRJ_DIR}/qspi_top.sv
${PRJ_DIR}/qspi_transmitter.sv
${PRJ_DIR}/qspi_xip.sv
${PRJ_DIR}/registers.svh
${PRJ_DIR}/rr_arb_tree.sv
${PRJ_DIR}/rstmgr.sv
${PRJ_DIR}/rv_plic_gateway.sv
${PRJ_DIR}/rv_plic_reg_top.sv
${PRJ_DIR}/rv_plic.sv
${PRJ_DIR}/rv_plic_target.sv
${PRJ_DIR}/rv_timer_reg_top.sv
${PRJ_DIR}/rv_timer.sv
${PRJ_DIR}/rx_timer.sv
${PRJ_DIR}/spi_clgen.sv
${PRJ_DIR}/spi_core.sv
${PRJ_DIR}/spi_shift.sv
${PRJ_DIR}/spi_top.sv
${PRJ_DIR}/tic.sv
${PRJ_DIR}/tic_top.sv
${PRJ_DIR}/timer_core.sv
${PRJ_DIR}/tlul_adapter_reg.sv
${PRJ_DIR}/tlul_err_resp.sv
${PRJ_DIR}/tlul_err.sv
${PRJ_DIR}/tlul_fifo_sync.sv
${PRJ_DIR}/tlul_host_adapter.sv
${PRJ_DIR}/tlul_socket_1n.sv
${PRJ_DIR}/tlul_sram_adapter.sv
${PRJ_DIR}/tlul_xbar_main.sv
${PRJ_DIR}/tlul_xbar_periph.sv

+incdir+${ARM_DIR}
${ARM_DIR}/sram_1024x32x4/sram_sp_hdc_svt_rvt_hvt.v
${ARM_DIR}/fifo/sram_fifo.v

${PRJ_DIR}/uart_core.sv
${PRJ_DIR}/uart_rx_prog.sv
${PRJ_DIR}/uart_rx.sv
${PRJ_DIR}/uart_top.sv
${PRJ_DIR}/uart_tx.sv


// OLD FILES
// pulp_fpnew files
//${FPU_DIR}/src/fpnew_top.sv
//${FPU_DIR}/src/fpnew_rounding.sv
//${FPU_DIR}/src/fpnew_opgroup_fmt_slice.sv
//${FPU_DIR}/src/fpnew_opgroup_multifmt_slice.sv
//${FPU_DIR}/src/fpnew_opgroup_block.sv  
//${FPU_DIR}/src/fpnew_noncomp.sv
//${FPU_DIR}/src/fpnew_fma.sv
//${FPU_DIR}/src/fpnew_fma_multi.sv
//${FPU_DIR}/src/fpnew_divsqrt_multi.sv
//${FPU_DIR}/src/fpnew_classifier.sv
//${FPU_DIR}/src/fpnew_cast_multi.sv

// OLD FILES
//${FPU_DIR}/src/common_cells/src/rr_arb_tree.sv
//${FPU_DIR}/src/common_cells/src/lzc.sv

// OLD FILES
//${FPU_DIR}/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv 
//${FPU_DIR}/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
//${FPU_DIR}/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv 
//${FPU_DIR}/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
//${FPU_DIR}/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
//${FPU_DIR}/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv


// Core DV files
${GEN_DIR}/src/riscv_signature_pkg.sv
+incdir+${DV_DIR}/env
+incdir+${DV_DIR}/tests
+incdir+${DV_DIR}/common/ibex_mem_intf_agent
+incdir+${DV_DIR}/common/irq_agent
+incdir+${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/mem_model
+incdir+${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/dv_utils
${DV_AZADI_TSMC}/random_tests/env/core/vendor/bus_params_pkg/bus_params_pkg.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/common_ifs/clk_rst_if.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/common_ifs/pins_if.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/dv_utils/dv_utils_pkg.sv
${DV_AZADI_TSMC}/random_tests/depencs/vendor/lowrisc_ip/mem_model/mem_model_pkg.sv
${DV_DIR}/common/ibex_mem_intf_agent/ibex_mem_intf.sv
${DV_DIR}/common/ibex_mem_intf_agent/ibex_mem_intf_agent_pkg.sv
${DV_DIR}/common/irq_agent/irq_if.sv
${DV_DIR}/common/irq_agent/irq_agent_pkg.sv
${DV_DIR}/env/core_ibex_instr_monitor_if.sv
${DV_DIR}/env/core_ibex_dut_probe_if.sv
${DV_DIR}/env/core_ibex_rvfi_if.sv
${DV_DIR}/env/core_ibex_csr_if.sv
${DV_DIR}/env/core_ibex_env_pkg.sv
${DV_DIR}/tests/core_ibex_test_pkg.sv
${DV_DIR}/fcov/core_ibex_fcov_if.sv
${DV_DIR}/fcov/core_ibex_fcov_bind.sv
${DV_DIR}/tb/core_ibex_tb_top.sv